// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

namespace Microsoft.CodeAnalysis.CSharp.iWareSql
{
    /// <summary>
    /// Source text for the [Orm]/[DbField] marker attributes, injected as an extra synthesized
    /// SyntaxTree into every CSharpCompilation (see CSharpCompilation.Create in
    /// Compilation/CSharpCompilation.cs) so that consuming projects never declare or reference
    /// these types themselves - they just write [Orm]/[DbField] and it resolves.
    ///
    /// OrmSchemaProvider (OrmSchema.cs) reads these back off the bound symbols by simple name,
    /// not by type identity, so each compilation getting its own private synthesized copy (e.g.
    /// a class library project and the app project that references it each have their own
    /// independently-synthesized internal OrmAttribute/DbFieldAttribute) is not a problem -
    /// OrmSchemaProvider's walk over a referenced assembly's [Orm] types still recognizes them.
    /// </summary>
    internal static class OrmAttributesSource
    {
        public const string Text = @"
// <auto-generated>
// Synthesized automatically by the compiler for every compilation. Not present on disk in your
// project - do not declare your own OrmAttribute/DbFieldAttribute, this is already provided.
// </auto-generated>
using System;

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
internal sealed class OrmAttribute : Attribute
{
    /// <summary>
    /// Optional - defaults to the class name if omitted.
    /// </summary>
    public string TableName { get; set; }
    /// <summary>
    /// Optional - defaults to false if omitted. Tells the compiler if the real table name should have the tenant ID suffix
    /// </summary>
    public bool NonTenantTable { get; set; }
}

[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
internal sealed class DbFieldAttribute : Attribute
{
    /// <summary>
    /// Optional - defaults to the property/field name if omitted.
    /// </summary>
    public string Label { get; set; }
    /// <summary>
    /// Optional - defaults to false if omitted. Should this public field not be used as a column.
    /// </summary>
    public bool Ignore { get; set; }
}
";
    }
}
