// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

namespace Microsoft.CodeAnalysis.CSharp.iWareSql
{
    /// <summary>
    /// Source text for the [Orm]/[DbField] marker attributes, injected as an extra synthesized
    /// SyntaxTree into every CSharpCompilation (see CSharpCompilation.Create in
    /// Compilation/CSharpCompilation.cs) so that consuming projects never declare or reference
    /// these types themselves - they just write [Orm]/[DbField] and it resolves.
    ///
    /// OrmSchemaProvider (OrmSchema.cs) reads these back off the bound symbols by simple name,
    /// not by type identity, so each compilation getting its own private synthesized copy (e.g.
    /// a class library project and the app project that references it each have their own
    /// independently-synthesized internal OrmAttribute/DbFieldAttribute) is not a problem -
    /// OrmSchemaProvider's walk over a referenced assembly's [Orm] types still recognizes them.
    /// </summary>
    internal static class TenantSessionSource
    {
        public const string Text = @"
// <auto-generated>
// Synthesized automatically by the compiler for every compilation. Not present on disk in your project
// </auto-generated>
";
    }
}
