// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

#pragma warning disable RS0016 // Add public types and members to the declared API
namespace Microsoft.CodeAnalysis.CSharp.iWareSql
{
    public static class SqlKeywords
    {
        public static readonly string[] SqlKeywordsList =
        [
            "SELECT",
            "DISTINCT",
            "TOP",
            "PERCENT",
            "WITH TIES",
            "AS",
            "FROM",
            "JOIN",
            "INNER JOIN",
            "LEFT JOIN",
            "LEFT OUTER JOIN",
            "RIGHT JOIN",
            "RIGHT OUTER JOIN",
            "FULL JOIN",
            "FULL OUTER JOIN",
            "CROSS JOIN",
            "CROSS APPLY",
            "OUTER APPLY",
            "ON",
            "WHERE",
            "GROUP BY",
            "HAVING",
            "ORDER BY",
            "ASC",
            "DESC",
            "OFFSET",
            "FETCH",
            "NEXT",
            "ROWS",
            "ROWS ONLY",
            "UNION",
            "UNION ALL",
            "INTERSECT",
            "EXCEPT",
            "AND",
            "OR",
            "NOT",
            "IN",
            "BETWEEN",
            "LIKE",
            "IS NULL",
            "IS NOT NULL",
            "EXISTS",
            "ANY",
            "ALL",
            "SOME",
            "CASE",
            "WHEN",
            "THEN",
            "ELSE",
            "END",
            "OVER",
            "PARTITION BY",
            "ROW_NUMBER",
            "RANK",
            "DENSE_RANK",
            "NTILE",
            "WITH",
            "PIVOT",
            "UNPIVOT",
            "FOR",
            "TABLESAMPLE",
            "INTO",
            "COUNT",
            "COUNT_BIG",
            "SUM",
            "AVG",
            "MIN",
            "MAX",
            "STDEV",
            "STDEVP",
            "VAR",
            "VARP",
            "GROUPING",
            "GROUPING_ID",
            "CHECKSUM_AGG",
            "STRING_AGG",
            "APPROX_COUNT_DISTINCT",
        ];
    }
}
#pragma warning restore RS0016 // Add public types and members to the declared API
